version: '3.4'
services:
  daily-dict:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: daily-dict
    volumes:
      - ./app:/app/
      - /app/node_modules
      - ./index.html:/site/index.html
    command:
    - sleep
    - infinity
