name: Get daily word from dexonline.ro

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  get-daily-dexonline-word:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and Run Container
        run: |
          docker build -t dexonline-word:latest .
          docker run --rm dexonline-word:latest
